name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml', 'setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e .[dev]; else pip install -r requirements.txt; fi

      - name: Lint (ruff)
        run: |
          ruff --version || pip install ruff
          ruff check src examples scripts tests

      # Temporarily disable black check; rely on ruff for linting.
      # Re-enable after repository auto-formatting is applied.

      - name: Type check (mypy)
        run: |
          mypy --version || pip install mypy
          mypy src

      - name: Tests (pytest)
        run: |
          pytest -q --maxfail=1 --disable-warnings


