name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch numpy matplotlib seaborn scipy pandas pytest
        pip install -r requirements.txt || true
    
    - name: Run tests
      run: |
        PYTHONPATH=$PWD pytest tests/test_poh_modules.py -v
    
    - name: Check imports
      run: |
        python -c "from src.pot.modules import PoHConfig, PoHStack, IterRefiner; print('✅ Core imports OK')"
        python -c "from src.pot.models import PoHGPT; print('✅ Model imports OK')"
    
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install ruff black
    
    - name: Check formatting with black
      run: |
        black --check src/ tests/ || echo "⚠️  Black formatting issues (non-blocking)"
      continue-on-error: true
    
    - name: Lint with ruff
      run: |
        ruff check src/ tests/ --exit-zero || echo "⚠️  Ruff linting issues (non-blocking)"
      continue-on-error: true

  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch numpy matplotlib seaborn scipy pandas pytest
    
    - name: Smoke test - PoH usage example
      run: |
        PYTHONPATH=$PWD python examples/poh_usage.py
    
    - name: Smoke test - PoHGPT usage example
      run: |
        PYTHONPATH=$PWD python examples/poh_gpt_usage.py
