name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e .; else pip install -r requirements.txt; fi

      - name: Package artifacts
        run: |
          mkdir -p dist_artifacts
          [ -f results.csv ] && cp results.csv dist_artifacts/ || true
          [ -f best_poh.pt ] && cp best_poh.pt dist_artifacts/ || true
          [ -d figures ] && tar -czf dist_artifacts/figures.tar.gz figures || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


